version: "3"

services:
  sample_db:
    image: mysql:5.7.16
    container_name: sample_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: sample_db
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpass
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.conf:/etc/mysql/conf.d/my.conf
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 3308:3308
    command: --port 3308
    tty: true

  fast_api_with_db:
    depends_on:
      - sample_db
    container_name: fast_api_with_db
    build: ./be
    ports:
      - 8000:8000
    volumes:
      - ./be/api:/usr/src/server